#!/bin/sh -l
# FILENAME:  slurmtest1.sub

echo $CUDA_VISIBLE_DEVICES
module load cuda/11.0.3
module load cudnn/cuda-11.0_8.0
#module load anaconda/2020.11-py38

# Change to the directory from which you originally submitted this job.
cd $SLURM_SUBMIT_DIR
#source activate mlparticleflow

CUDA_VISIBLE_DEVICES=0,1 singularity exec --nv tensorflowflow3.sif python3 mlpf/launcher.py --action train --model-spec parameters/cms-gnn-dense.yaml
